const express = require('express');
const cors = require('cors');
const app = express();
const PORT = 3001;

app.use(cors());

const dogFacts = [
    "Dogs have three eyelids.",
    "A dog’s sense of smell is 40 times better than a human’s.",
    "Some dogs can learn more than 1,000 words.",
    "Dalmatian puppies are born completely white.",
    "A Greyhound could beat a Cheetah in a long-distance race.",
    "Dogs can smell your feelings.",
    "The Basenji dog is known for not barking.",
    "Dogs’ noses are wet to help absorb scent chemicals.",
    "The Labrador Retriever is the most popular dog breed in the U.S.",
    "Dogs dream just like humans.",
    "Dogs have about 1,700 taste buds, compared to humans who have about 9,000.",
    "The Saluki is the oldest dog breed, dating back to ancient Egypt.",
    "Dogs sweat through their paw pads.",
    "A Bloodhound’s sense of smell can be used as evidence in court.",
    "Dogs can hear 4 times as far as humans.",
    "Yawning is contagious between dogs and their owners.",
    "The Norwegian Lundehund has six toes on each foot.",
    "Dogs curl up to protect their organs when they sleep.",
    "Dogs can understand up to 250 words and gestures.",
    "Puppies are born deaf and blind.",
    "The world's smallest dog breed is the Chihuahua.",
    "Dogs’ noses can detect heat and thermal radiation.",
    "Dogs are as smart as a two-year-old child.",
    "The shape of a dog’s face can hint at its lifespan — longer faces generally mean longer lives.",
    "Some dogs are trained to detect medical conditions like seizures or low blood sugar.",
    "Newfoundlands are great swimmers due to their webbed feet.",
    "Dogs have been our companions for at least 14,000 years.",
    "Tail wagging has its own language — different wags mean different emotions.",
    "Dogs can see in the dark much better than humans.",
    "Each dog’s nose print is unique, like a human fingerprint.",
    "Dogs can detect cancer through their sense of smell.",
    "Dogs have an extraordinary sense of time and can predict future events, like regular walk times.",
    "Dogs are capable of empathy and will try to comfort you when you’re sad.",
    "The Beagle is one of the best sniffers in the dog world.",
    "Dogs have around 300 million olfactory receptors in their noses.",
    "Dogs’ whiskers are touch-sensitive hairs called vibrissae.",
    "A dog’s sense of smell is 10,000 to 100,000 times more acute than ours.",
    "A puppy is born toothless and only grows baby teeth at 3 weeks.",
    "Dogs communicate with each other through a complex system of vocalization and body language.",
    "The fastest breed of dog is the Greyhound, reaching up to 45 mph.",
    "Dogs can be left- or right-pawed, just like humans are left- or right-handed.",
    "The average dog can understand about 165 words, signs, and signals.",
    "The Alaskan Malamute is one of the oldest Arctic sled dog breeds.",
    "Dogs have dreams just like humans, often involving their daily activities.",
    "Service dogs are trained to assist people with a wide range of disabilities.",
    "A dog’s mouth exerts up to 320 pounds of pressure.",
    "Puppies begin to open their eyes around 10 to 14 days after birth.",
    "Some dogs can detect earthquakes before they happen.",
    "The wetness of a dog’s nose helps it determine the direction of a smell.",
    "Dogs can detect drops in blood sugar levels for people with diabetes.",
    "The average dog’s heart rate is 60 to 140 beats per minute.",
    "Dogs have twice as many muscles in their ears as humans.",
    "The sense of smell in dogs can be trained for search and rescue, cadaver detection, and narcotics.",
    "Dogs have a higher body temperature than humans: about 101 to 102.5°F.",
    "A dog’s wagging tail doesn’t always mean it’s happy.",
    "Dogs can be trained to sniff out bed bugs and termites.",
    "Puppies grow rapidly in the first year and reach adult size by 12-18 months.",
    "Dogs have been shown to respond positively to classical music.",
    "Dogs prefer to poop along a north-south axis aligned with the Earth’s magnetic field.",
    "The average dog sleeps about 12-14 hours a day.",
    "Dogs can get jealous when their owners show affection to others.",
    "The Border Collie is considered the most intelligent dog breed.",
    "Some dogs are trained to sniff out electronics to help law enforcement.",
    "Dogs are pack animals and are naturally social.",
    "The Great Dane is the tallest dog breed.",
    "The Irish Wolfhound is also among the tallest breeds.",
    "Dachshunds were originally bred to hunt badgers.",
    "The Poodle is known for being hypoallergenic.",
    "The Shih Tzu was bred to be a royal lap dog in China.",
    "Dogs use their tails to express a wide range of emotions.",
    "Dogs can see in shades of blue and yellow, not red and green.",
    "Dogs pant to cool themselves because they don’t have sweat glands like humans.",
    "Dogs love routine and feel more secure when they follow one.",
    "Dogs can feel lonely and anxious without proper companionship.",
    "A dog’s ears are incredibly expressive with over 18 muscles controlling them.",
    "Puppies learn socialization skills from their littermates.",
    "Dogs use smell to communicate and mark territory.",
    "Dogs can suffer from depression and anxiety, just like humans.",
    "Huskies have special eyes that help them withstand Arctic glare.",
    "Dogs can detect changes in barometric pressure and storms.",
    "Dogs have a “third eyelid” called the nictitating membrane.",
    "The average lifespan of a dog is 10 to 13 years.",
    "Spaying or neutering your dog can help prevent health issues and overpopulation.",
    "Dogs thrive on mental stimulation and physical exercise.",
    "The Saint Bernard was originally bred for rescue in the Alps.",
    "The Australian Cattle Dog holds the record for oldest living dog — 29 years!",
    "Dogs can get sunburn, especially those with light skin or fur.",
    "The Basset Hound has one of the best senses of smell.",
    "The Cocker Spaniel has the largest ears of any breed.",
    "Chihuahuas have the largest brain-to-body ratio of any breed.",
    "Dalmatians are born without spots — they develop them as they grow.",
    "Dogs tilt their heads to adjust their outer ears and better pinpoint sounds.",
    "Some dogs are trained to detect peanuts for people with severe allergies.",
    "Dogs mark their territory with scent glands in their paws.",
    "A group of pugs is called a grumble.",
    "Dogs have a “sweet spot” on their belly that makes their leg kick when scratched.",
    "A dog’s nose has as many as 300 million scent receptors.",
    "Dogs have a special membrane called the tapetum lucidum to see in the dark.",
    "Golden Retrievers were originally bred to retrieve game from water.",
    "Labradors come in three colors: yellow, black, and chocolate.",
    "Dogs can interpret human facial expressions and tone of voice.",
    "Dogs prefer human companionship over food in many studies.",
    "Petting a dog can lower your blood pressure.",
    "Dogs have a stronger sense of smell than any other animal.",
    "Some dogs can be trained to detect COVID-19 and other diseases.",
    "Dogs sweat only through the pads of their feet.",
    "Dogs learn best through positive reinforcement.",
    "Many dogs enjoy problem-solving games like treat puzzles.",
    "Dogs wag their tails to the right when happy and left when anxious.",
    "Dogs bond deeply with their owners and show loyalty for life.",
    "Dogs are descendants of wolves but were domesticated over thousands of years.",
    "Small breeds often live longer than large breeds.",
    "Some dogs are allergic to human dander.",
    "Dogs can understand pointing gestures, something even some primates can’t do.",
    "Dogs have fewer taste buds for sweetness than humans.",
    "Dogs can hear sounds between 40 Hz to 60,000 Hz — humans only hear up to 20,000 Hz.",
    "Dogs rely on routine and consistency for training success.",
    "Dogs can recognize themselves in mirrors by scent, not sight.",
    "Dogs chase their tails for exercise, curiosity, or anxiety.",
    "Older dogs may get dementia or cognitive dysfunction.",
    "Dogs learn from observing other dogs and people.",
    "Many military and police dogs are trained in multiple languages.",
    "Dogs use calming signals like yawning or licking to ease tension.",
    "Dogs may lick people to show affection or request attention.",
    "Certain breeds are more vocal than others, like Beagles and Huskies.",
    "Dogs can become stressed by loud sounds, such as fireworks or thunder.",
    "Proper socialization is crucial for puppies in the first 12 weeks.",
    "Dogs don’t like hugs — it can feel like a trap to them.",
    "Dogs with long ears, like Basset Hounds, stir up scents as they walk.",
    "Canine intelligence includes problem-solving and emotional understanding.",
    "Dogs can grieve the loss of companions, human or canine.",
    "Dogs have excellent peripheral vision due to the position of their eyes.",
    "Smaller dogs often have faster heartbeats than larger dogs.",
    "Therapy dogs help reduce anxiety and increase oxytocin levels.",
    "Dogs roll in smelly things to mask their own scent — a leftover trait from wild ancestors.",
    "Dogs in movies are often trained to respond to silent hand signals.",
    "Dogs can see movement better than humans, especially in low light.",
    "Dogs can be lactose intolerant.",
    "Some dogs love swimming, but not all breeds are natural swimmers.",
    "Dogs prefer praise over treats in many situations.",
    "The more a dog wags its tail, the more excited it is — not always happy, sometimes nervous.",
    "Dogs have about 42 teeth.",
    "Senior dogs need different nutrition and care than puppies.",
    "Dogs can develop arthritis, just like humans.",
    "Dogs can be taught to use buttons to communicate words.",
    "Dogs enjoy routine and predictability to reduce anxiety.",
    "A “zoomie” is when a dog runs around excitedly for a few minutes.",
    "Dogs' eyes glow in photos due to the tapetum lucidum.",
    "Dogs remember positive and negative experiences vividly.",
    "Dogs have been shown to detect changes in human hormone levels.",
    "Dogs often sniff each other’s behinds as a form of greeting.",
    "Dogs with floppy ears are more prone to ear infections.",
    "Dogs’ personalities are influenced by breed and upbringing."
];

app.get('/', (req, res) => {
    res.send('🐶 Welcome to the Dog Facts API! Use /api/dog-fact to get a random fact.');
});

app.get('/api/dog-fact', (req, res) => {
    const randomFact = dogFacts[Math.floor(Math.random() * dogFacts.length)];
    res.json({ fact: randomFact });
});

app.listen(PORT, () => {
    console.log(`Dog Facts API running at http://localhost:${PORT}`);
});
